[project]
name = "day-10"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12.4"
dependencies = [
    "black>=24.10.0",
    "flake8>=7.1.1",
    "jedi>=0.19.2",
    "numpy>=2.2.0",
    "pip>=24.3.1",
]
